[package]
name = "rust_graph_util"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
graphalgs = "0.1.1"
itertools = "0.11.0"
num = "0.4.1"
petgraph = "0.6.4"
